'use client'

import Image from 'next/image'
import Link from 'next/link'
import { ArrowRight, Building2, CheckCircle2, Landmark, MapPin, ShieldCheck, Sparkles } from 'lucide-react'
import { useCasaLocale } from '@/components/use-casa-locale'
import type { LocaleCode } from '@/lib/i18n'

const network = [
  ['Roma', 'Italia', '🇮🇹', 'heritage'], ['San José', 'Costa Rica', '🇨🇷', 'operating'],
  ['Milano', 'Italia', '🇮🇹', 'coordination'], ['Madrid', 'España', '🇪🇸', 'market'],
  ['Barcelona', 'España', '🇪🇸', 'market'], ['Sevilla', 'España', '🇪🇸', 'market'],
  ['Andorra la Vella', 'Andorra', '🇦🇩', 'market'], ['Zürich · Genève', 'Suiza', '🇨🇭', 'market'],
  ['Paris', 'Francia', '🇫🇷', 'market'], ['Frankfurt', 'Alemania', '🇩🇪', 'market'],
  ['Warszawa', 'Polonia', '🇵🇱', 'market'], ['Moskva', 'Rusia', '🇷🇺', 'market'],
  ['New York', 'Estados Unidos', '🇺🇸', 'market'], ['Hong Kong', 'China', '🇭🇰', 'market'],
] as const

type HomeCopy = {
  eyebrow: string; titleA: string; titleB: string; intro: string; casa: string; book: string
  heritage: string; heritageTitle: string; rome: string; costaRica: string
  institution: string; institutionTitle: string; institutionBody: string
  principles: [string, string][]; network: string; networkTitle: string; networkBody: string
  statuses: Record<string, string>; networkNote: string
  europe: string; europeTitle: string; europeBody: string; europeNote: string
  health: string; healthBody: string; start: string; contact: string
}

const c: Record<LocaleCode, HomeCopy> = {
  es: {
    eyebrow:'Casa italiana de vocación internacional', titleA:'Desde Roma,', titleB:'con horizonte generacional.',
    intro:'Casa Bernocchi preserva una herencia institucional iniciada en Roma en 1893 y desarrolla, desde 2024, una operación regional en Costa Rica. Conocimiento, honor, disciplina y legado convertidos en sistemas verificables.',
    casa:'Conocer la Casa', book:'Solicitar una cita', heritage:'Herencia institucional', heritageTitle:'Un origen. Una apertura. Una arquitectura para el porvenir.',
    rome:'Fundación histórica de Casa Bernocchi en Roma, Italia, como punto de origen de su tradición institucional.', costaRica:'Apertura de la operación regional en Costa Rica y comienzo de la etapa contemporánea de la Casa.',
    institution:'La institución', institutionTitle:'No acumulamos servicios. Construimos instituciones.', institutionBody:'La Casa gobierna cultura, continuidad y reputación. Cada institución responde a una disciplina, una gobernanza y un estándar común.',
    principles:[['Scientia','Conocimiento verificado antes de cada decisión.'],['Honor','Integridad, palabra institucional y responsabilidad.'],['Disciplina','Ejecución documentada, sobria y constante.'],['Legado','Valor construido más allá del ciclo inmediato.']],
    network:'Presencia y proyección', networkTitle:'Una red internacional con estatus declarado.', networkBody:'Distinguimos operaciones activas, coordinación europea y mercados estratégicos. La ambición nunca sustituye la precisión institucional.',
    statuses:{heritage:'Origen histórico',operating:'Operación activa',coordination:'Coordinación europea',market:'Mercado estratégico'}, networkNote:'“Mercado estratégico” representa proyección comercial e institucional; no constituye por sí mismo una oficina física abierta al público.',
    europe:'Orientación europea', europeTitle:'Excelencia, discreción y permanencia.', europeBody:'La identidad visual y operativa adopta sobriedad, protección de datos, trazabilidad y calidad institucional de vocación europea e internacional.', europeNote:'La bandera europea expresa orientación geográfica e institucional. No implica aprobación, patrocinio ni afiliación oficial con la Unión Europea.',
    health:'Bernocchi Health', healthBody:'Atención profesional, confidencial y estructurada. El proceso guía automáticamente desde el servicio y la modalidad hasta los datos, disponibilidad y reserva provisional.', start:'Iniciar solicitud', contact:'Contactar la Segreteria',
  },
  en: {
    eyebrow:'An Italian house with international vocation', titleA:'From Rome,', titleB:'built for generations.',
    intro:'Casa Bernocchi preserves an institutional heritage begun in Rome in 1893 and, since 2024, develops regional operations in Costa Rica. Knowledge, honour, discipline and legacy translated into verifiable systems.',
    casa:'Discover the House', book:'Request an appointment', heritage:'Institutional heritage', heritageTitle:'One origin. One opening. An architecture for the future.',
    rome:'Historical foundation of Casa Bernocchi in Rome, Italy, as the origin of its institutional tradition.', costaRica:'Opening of regional operations in Costa Rica and beginning of the House’s contemporary chapter.',
    institution:'The institution', institutionTitle:'We do not accumulate services. We build institutions.', institutionBody:'The House governs culture, continuity and reputation. Each institution follows a discipline, a governance model and a shared standard.',
    principles:[['Scientia','Verified knowledge before every decision.'],['Honour','Integrity, institutional word and accountability.'],['Discipline','Documented, sober and consistent execution.'],['Legacy','Value built beyond the immediate cycle.']],
    network:'Presence and outlook', networkTitle:'An international network with declared status.', networkBody:'We distinguish active operations, European coordination and strategic markets. Ambition never replaces institutional accuracy.',
    statuses:{heritage:'Historical origin',operating:'Active operation',coordination:'European coordination',market:'Strategic market'}, networkNote:'“Strategic market” represents commercial and institutional outlook; it does not by itself constitute a public-facing physical office.',
    europe:'European orientation', europeTitle:'Excellence, discretion and permanence.', europeBody:'The visual and operating identity adopts restraint, data protection, traceability and institutional quality with European and international vocation.', europeNote:'The European flag expresses geographic and institutional orientation. It does not imply approval, sponsorship or official affiliation with the European Union.',
    health:'Bernocchi Health', healthBody:'Professional, confidential and structured care. The journey automatically guides visitors from service and mode to details, availability and provisional reservation.', start:'Start request', contact:'Contact the Segreteria',
  },
  it: {
    eyebrow:'Casa italiana a vocazione internazionale', titleA:'Da Roma,', titleB:'con orizzonte generazionale.',
    intro:'Casa Bernocchi custodisce un’eredità istituzionale iniziata a Roma nel 1893 e, dal 2024, sviluppa un’operatività regionale in Costa Rica. Conoscenza, onore, disciplina e lascito tradotti in sistemi verificabili.',
    casa:'Conoscere la Casa', book:'Richiedere un appuntamento', heritage:'Eredità istituzionale', heritageTitle:'Un’origine. Un’apertura. Un’architettura per il futuro.',
    rome:'Fondazione storica di Casa Bernocchi a Roma, Italia, quale origine della sua tradizione istituzionale.', costaRica:'Apertura dell’operatività regionale in Costa Rica e inizio della fase contemporanea della Casa.',
    institution:'L’istituzione', institutionTitle:'Non accumuliamo servizi. Costruiamo istituzioni.', institutionBody:'La Casa governa cultura, continuità e reputazione. Ogni istituzione risponde a una disciplina, una governance e uno standard comune.',
    principles:[['Scientia','Conoscenza verificata prima di ogni decisione.'],['Onore','Integrità, parola istituzionale e responsabilità.'],['Disciplina','Esecuzione documentata, sobria e costante.'],['Lascito','Valore costruito oltre il ciclo immediato.']],
    network:'Presenza e proiezione', networkTitle:'Una rete internazionale con status dichiarato.', networkBody:'Distinguiamo operatività attive, coordinamento europeo e mercati strategici. L’ambizione non sostituisce mai la precisione istituzionale.',
    statuses:{heritage:'Origine storica',operating:'Operatività attiva',coordination:'Coordinamento europeo',market:'Mercato strategico'}, networkNote:'“Mercato strategico” indica proiezione commerciale e istituzionale; non costituisce da solo un ufficio fisico aperto al pubblico.',
    europe:'Orientamento europeo', europeTitle:'Eccellenza, discrezione e permanenza.', europeBody:'L’identità visiva e operativa adotta sobrietà, protezione dei dati, tracciabilità e qualità istituzionale a vocazione europea e internazionale.', europeNote:'La bandiera europea esprime orientamento geografico e istituzionale. Non implica approvazione, patrocinio o affiliazione ufficiale con l’Unione europea.',
    health:'Bernocchi Health', healthBody:'Assistenza professionale, riservata e strutturata. Il percorso guida automaticamente dal servizio e dalla modalità ai dati, alla disponibilità e alla prenotazione provvisoria.', start:'Iniziare la richiesta', contact:'Contattare la Segreteria',
  },
  fr: {
    eyebrow:'Maison italienne à vocation internationale', titleA:'Depuis Rome,', titleB:'pour les générations à venir.', intro:'Casa Bernocchi préserve un héritage institutionnel né à Rome en 1893 et développe, depuis 2024, une activité régionale au Costa Rica. Connaissance, honneur, discipline et héritage transformés en systèmes vérifiables.',
    casa:'Découvrir la Maison',book:'Demander un rendez-vous',heritage:'Héritage institutionnel',heritageTitle:'Une origine. Une ouverture. Une architecture pour l’avenir.',rome:'Fondation historique de Casa Bernocchi à Rome, en Italie, origine de sa tradition institutionnelle.',costaRica:'Ouverture de l’activité régionale au Costa Rica et début du chapitre contemporain de la Maison.',institution:'L’institution',institutionTitle:'Nous n’accumulons pas des services. Nous bâtissons des institutions.',institutionBody:'La Maison gouverne la culture, la continuité et la réputation. Chaque institution suit une discipline, une gouvernance et un standard communs.',principles:[['Scientia','La connaissance vérifiée avant chaque décision.'],['Honneur','Intégrité, parole institutionnelle et responsabilité.'],['Discipline','Exécution documentée, sobre et constante.'],['Héritage','Une valeur construite au-delà du cycle immédiat.']],network:'Présence et projection',networkTitle:'Un réseau international au statut déclaré.',networkBody:'Nous distinguons activité, coordination européenne et marchés stratégiques. L’ambition ne remplace jamais la précision.',statuses:{heritage:'Origine historique',operating:'Activité active',coordination:'Coordination européenne',market:'Marché stratégique'},networkNote:'« Marché stratégique » représente une projection commerciale et institutionnelle, et non un bureau physique ouvert au public.',europe:'Orientation européenne',europeTitle:'Excellence, discrétion et permanence.',europeBody:'L’identité adopte sobriété, protection des données, traçabilité et qualité institutionnelle de vocation européenne et internationale.',europeNote:'Le drapeau européen exprime une orientation géographique et institutionnelle sans approbation, parrainage ni affiliation officielle.',health:'Bernocchi Health',healthBody:'Des soins professionnels, confidentiels et structurés. Le parcours guide automatiquement du service à la réservation provisoire.',start:'Commencer la demande',contact:'Contacter la Segreteria',
  },
  de: {
    eyebrow:'Italienisches Haus mit internationaler Ausrichtung',titleA:'Aus Rom,',titleB:'für Generationen gebaut.',intro:'Casa Bernocchi bewahrt ein institutionelles Erbe, das 1893 in Rom begann, und entwickelt seit 2024 regionale Aktivitäten in Costa Rica. Wissen, Ehre, Disziplin und Vermächtnis werden in überprüfbare Systeme übersetzt.',casa:'Das Haus entdecken',book:'Termin anfragen',heritage:'Institutionelles Erbe',heritageTitle:'Ein Ursprung. Eine Eröffnung. Eine Architektur für die Zukunft.',rome:'Historische Gründung von Casa Bernocchi in Rom als Ursprung ihrer institutionellen Tradition.',costaRica:'Eröffnung der regionalen Tätigkeit in Costa Rica und Beginn des zeitgenössischen Kapitels.',institution:'Die Institution',institutionTitle:'Wir sammeln keine Dienstleistungen. Wir bauen Institutionen.',institutionBody:'Das Haus steuert Kultur, Kontinuität und Reputation. Jede Institution folgt Disziplin, Governance und gemeinsamem Standard.',principles:[['Scientia','Geprüftes Wissen vor jeder Entscheidung.'],['Ehre','Integrität, institutionelles Wort und Verantwortung.'],['Disziplin','Dokumentierte, nüchterne und beständige Umsetzung.'],['Vermächtnis','Wert über den unmittelbaren Zyklus hinaus.']],network:'Präsenz und Ausblick',networkTitle:'Ein internationales Netzwerk mit ausgewiesenem Status.',networkBody:'Aktiver Betrieb, europäische Koordination und strategische Märkte werden klar unterschieden.',statuses:{heritage:'Historischer Ursprung',operating:'Aktiver Betrieb',coordination:'Europäische Koordination',market:'Strategischer Markt'},networkNote:'„Strategischer Markt“ ist eine kommerzielle Perspektive, nicht automatisch ein öffentliches physisches Büro.',europe:'Europäische Orientierung',europeTitle:'Exzellenz, Diskretion und Beständigkeit.',europeBody:'Die Identität folgt Zurückhaltung, Datenschutz, Nachvollziehbarkeit und institutioneller Qualität.',europeNote:'Die Europaflagge bedeutet keine Genehmigung, Förderung oder offizielle Verbindung zur Europäischen Union.',health:'Bernocchi Health',healthBody:'Professionelle, vertrauliche und strukturierte Betreuung mit automatischem Reservierungsablauf.',start:'Anfrage starten',contact:'Segreteria kontaktieren',
  },
  ca: {
    eyebrow:'Casa italiana amb vocació internacional',titleA:'Des de Roma,',titleB:'amb horitzó generacional.',intro:'Casa Bernocchi preserva una herència institucional iniciada a Roma el 1893 i, des del 2024, desenvolupa operacions regionals a Costa Rica. Coneixement, honor, disciplina i llegat convertits en sistemes verificables.',casa:'Conèixer la Casa',book:'Sol·licitar una cita',heritage:'Herència institucional',heritageTitle:'Un origen. Una obertura. Una arquitectura per al futur.',rome:'Fundació històrica de Casa Bernocchi a Roma com a origen de la seva tradició institucional.',costaRica:'Obertura de l’operació regional a Costa Rica i inici de l’etapa contemporània.',institution:'La institució',institutionTitle:'No acumulem serveis. Construïm institucions.',institutionBody:'La Casa governa cultura, continuïtat i reputació. Cada institució respon a disciplina, governança i estàndard comú.',principles:[['Scientia','Coneixement verificat abans de cada decisió.'],['Honor','Integritat, paraula institucional i responsabilitat.'],['Disciplina','Execució documentada, sòbria i constant.'],['Llegat','Valor més enllà del cicle immediat.']],network:'Presència i projecció',networkTitle:'Una xarxa internacional amb estatus declarat.',networkBody:'Distingim operacions actives, coordinació europea i mercats estratègics.',statuses:{heritage:'Origen històric',operating:'Operació activa',coordination:'Coordinació europea',market:'Mercat estratègic'},networkNote:'“Mercat estratègic” representa projecció comercial, no una oficina física oberta al públic.',europe:'Orientació europea',europeTitle:'Excel·lència, discreció i permanència.',europeBody:'La identitat adopta sobrietat, protecció de dades, traçabilitat i qualitat institucional.',europeNote:'La bandera europea no implica aprovació, patrocini ni afiliació oficial amb la Unió Europea.',health:'Bernocchi Health',healthBody:'Atenció professional, confidencial i estructurada amb un procés automàtic de reserva.',start:'Iniciar sol·licitud',contact:'Contactar la Segreteria',
  },
  zh: {
    eyebrow:'具有国际视野的意大利机构之家',titleA:'源自罗马，',titleB:'面向世代传承。',intro:'Casa Bernocchi 传承始于1893年罗马的机构传统，并自2024年起在哥斯达黎加开展区域运营。将知识、荣誉、纪律与传承转化为可验证的体系。',casa:'了解 Casa Bernocchi',book:'申请预约',heritage:'机构传承',heritageTitle:'一个起点。一次启程。面向未来的架构。',rome:'Casa Bernocchi 于意大利罗马的历史创立，是其机构传统的起点。',costaRica:'2024年在哥斯达黎加启动区域运营，开启当代篇章。',institution:'机构体系',institutionTitle:'我们不堆叠服务，而是建设机构。',institutionBody:'Casa Bernocchi 统筹文化、连续性与声誉；每个机构遵循明确治理与共同标准。',principles:[['Scientia','每项决策之前先有经验证的知识。'],['荣誉','诚信、机构承诺与责任。'],['纪律','有记录、克制且持续的执行。'],['传承','超越短期周期构建长期价值。']],network:'布局与展望',networkTitle:'状态透明的国际网络。',networkBody:'明确区分实际运营、欧洲协调与战略市场。',statuses:{heritage:'历史起源',operating:'实际运营',coordination:'欧洲协调',market:'战略市场'},networkNote:'“战略市场”代表商业展望，并不等同于实体办公室。',europe:'欧洲导向',europeTitle:'卓越、审慎与长期主义。',europeBody:'视觉和运营体系遵循数据保护、可追溯性与机构质量标准。',europeNote:'欧洲旗帜不代表欧盟批准、赞助或官方隶属。',health:'Bernocchi Health',healthBody:'专业、保密、结构化服务，自动引导至临时预约。',start:'开始申请',contact:'联系 Segreteria',
  },
  pl: {
    eyebrow:'Włoski dom o międzynarodowym powołaniu',titleA:'Z Rzymu,',titleB:'z perspektywą pokoleń.',intro:'Casa Bernocchi zachowuje dziedzictwo zapoczątkowane w Rzymie w 1893 roku, a od 2024 roku rozwija działalność regionalną w Kostaryce. Wiedza, honor, dyscyplina i dziedzictwo w weryfikowalnych systemach.',casa:'Poznaj Dom',book:'Poproś o wizytę',heritage:'Dziedzictwo instytucjonalne',heritageTitle:'Jedno źródło. Jedno otwarcie. Architektura przyszłości.',rome:'Historyczne założenie Casa Bernocchi w Rzymie jako początek tradycji instytucjonalnej.',costaRica:'Otwarcie działalności regionalnej w Kostaryce i początek współczesnego rozdziału.',institution:'Instytucja',institutionTitle:'Nie gromadzimy usług. Budujemy instytucje.',institutionBody:'Dom zarządza kulturą, ciągłością i reputacją. Każda instytucja działa według wspólnego standardu.',principles:[['Scientia','Zweryfikowana wiedza przed każdą decyzją.'],['Honor','Integralność i odpowiedzialność.'],['Dyscyplina','Udokumentowane i konsekwentne wykonanie.'],['Dziedzictwo','Wartość poza krótkim cyklem.']],network:'Obecność i perspektywa',networkTitle:'Międzynarodowa sieć z jasnym statusem.',networkBody:'Rozróżniamy działalność, koordynację europejską i rynki strategiczne.',statuses:{heritage:'Początek historyczny',operating:'Aktywna działalność',coordination:'Koordynacja europejska',market:'Rynek strategiczny'},networkNote:'„Rynek strategiczny” nie stanowi sam w sobie fizycznego biura.',europe:'Orientacja europejska',europeTitle:'Doskonałość, dyskrecja i trwałość.',europeBody:'Identyfikacja przyjmuje ochronę danych, identyfikowalność i jakość instytucjonalną.',europeNote:'Flaga europejska nie oznacza zatwierdzenia ani oficjalnego powiązania z UE.',health:'Bernocchi Health',healthBody:'Profesjonalna, poufna i uporządkowana opieka z automatycznym procesem rezerwacji.',start:'Rozpocznij zgłoszenie',contact:'Skontaktuj się z Segreteria',
  },
  ru: {
    eyebrow:'Итальянский дом международного призвания',titleA:'Из Рима,',titleB:'с горизонтом поколений.',intro:'Casa Bernocchi хранит наследие, начатое в Риме в 1893 году, и с 2024 года развивает региональную деятельность в Коста-Рике. Знание, честь, дисциплина и наследие преобразованы в проверяемые системы.',casa:'Узнать о Доме',book:'Запросить приём',heritage:'Институциональное наследие',heritageTitle:'Одно начало. Одно открытие. Архитектура будущего.',rome:'Историческое основание Casa Bernocchi в Риме как начало институциональной традиции.',costaRica:'Открытие региональной деятельности в Коста-Рике и начало современной главы.',institution:'Институт',institutionTitle:'Мы не накапливаем услуги. Мы строим институты.',institutionBody:'Дом управляет культурой, преемственностью и репутацией по общему стандарту.',principles:[['Scientia','Проверенное знание до каждого решения.'],['Честь','Целостность и ответственность.'],['Дисциплина','Документированное и последовательное исполнение.'],['Наследие','Ценность за пределами краткого цикла.']],network:'Присутствие и перспектива',networkTitle:'Международная сеть с заявленным статусом.',networkBody:'Активная деятельность, европейская координация и стратегические рынки разделены.',statuses:{heritage:'Историческое начало',operating:'Активная деятельность',coordination:'Европейская координация',market:'Стратегический рынок'},networkNote:'«Стратегический рынок» не означает физический офис.',europe:'Европейская ориентация',europeTitle:'Совершенство, конфиденциальность и долговечность.',europeBody:'Идентичность следует защите данных, прослеживаемости и институциональному качеству.',europeNote:'Флаг Европы не означает одобрение или официальную связь с ЕС.',health:'Bernocchi Health',healthBody:'Профессиональная и конфиденциальная помощь с автоматическим процессом записи.',start:'Начать запрос',contact:'Связаться с Segreteria',
  },
  ja: {
    eyebrow:'国際的使命を持つイタリアの機関之家',titleA:'ローマから、',titleB:'世代を超える未来へ。',intro:'Casa Bernocchi は1893年にローマで始まった制度的伝統を受け継ぎ、2024年からコスタリカで地域運営を展開しています。知識、名誉、規律、遺産を検証可能な仕組みに変えます。',casa:'Casa Bernocchi を知る',book:'予約を申し込む',heritage:'制度的遺産',heritageTitle:'一つの起源。一つの始動。未来のための構造。',rome:'ローマにおける歴史的創設は制度的伝統の起点です。',costaRica:'2024年にコスタリカで地域運営を開始し、現代的章が始まりました。',institution:'機関',institutionTitle:'サービスを寄せ集めず、機関を築きます。',institutionBody:'Casa Bernocchi は文化、継続性、信用を共通基準で統治します。',principles:[['Scientia','意思決定に先立つ検証済みの知識。'],['名誉','誠実さと責任。'],['規律','記録され継続的な実行。'],['遺産','短期循環を超える価値。']],network:'拠点と展望',networkTitle:'位置づけを明示した国際ネットワーク。',networkBody:'運営、欧州調整、戦略市場を明確に区別します。',statuses:{heritage:'歴史的起源',operating:'稼働中',coordination:'欧州調整',market:'戦略市場'},networkNote:'「戦略市場」は物理的オフィスを意味しません。',europe:'欧州志向',europeTitle:'卓越性、慎重さ、持続性。',europeBody:'データ保護、追跡可能性、制度的品質を採用します。',europeNote:'欧州旗はEUの承認・後援・公式提携を意味しません。',health:'Bernocchi Health',healthBody:'専門的で機密性の高いケアと自動予約フロー。',start:'申請を開始',contact:'Segreteria に連絡',
  },
}

function Label({children}:{children:React.ReactNode}) {
  return <p className="text-[0.68rem] font-semibold uppercase tracking-[0.28em] text-[#c9a85f]">{children}</p>
}

export function PremiumHome() {
  const { locale } = useCasaLocale()
  const t = c[locale]
  return <div className="overflow-hidden bg-[#07131f] text-[#f7f1e6]">
    <section className="relative isolate min-h-[88svh] overflow-hidden border-b border-white/10">
      <Image src="/images/casa-bernocchi-institutional.jpeg" alt="Casa Bernocchi institutional architecture" fill priority className="object-cover opacity-42 [filter:saturate(.65)_contrast(1.05)]" sizes="100vw" />
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_72%_18%,rgba(194,155,75,.2),transparent_34%),linear-gradient(90deg,#06111c_3%,rgba(6,17,28,.96)_44%,rgba(6,17,28,.52)_76%,rgba(6,17,28,.85))]" />
      <div className="absolute inset-0 opacity-[.1] [background-image:linear-gradient(rgba(255,255,255,.13)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.13)_1px,transparent_1px)] [background-size:72px_72px]" />
      <div className="relative mx-auto flex min-h-[88svh] max-w-7xl items-center px-6 py-24 lg:px-10 lg:py-32"><div className="max-w-4xl">
        <div className="cb-rise inline-flex items-center gap-3 rounded-full border border-[#c9a85f]/35 bg-black/20 px-4 py-2 backdrop-blur-xl"><Sparkles className="size-3.5 text-[#d8bd7a]" /><span className="text-[.66rem] font-semibold uppercase tracking-[.24em] text-[#e6d09c]">{t.eyebrow}</span></div>
        <h1 className="mt-8 text-balance font-serif text-5xl font-light leading-[.94] tracking-[-.035em] sm:text-6xl lg:text-[6.5rem]"><span className="cb-rise block" style={{animationDelay:'120ms'}}>{t.titleA}</span><span className="cb-rise mt-2 block bg-gradient-to-r from-[#f8f1e3] via-[#e8d6ad] to-[#b79047] bg-clip-text text-transparent" style={{animationDelay:'220ms'}}>{t.titleB}</span></h1>
        <p className="cb-rise mt-8 max-w-2xl text-pretty text-base leading-8 text-white/70 sm:text-lg" style={{animationDelay:'340ms'}}>{t.intro}</p>
        <div className="cb-rise mt-10 flex flex-col gap-4 sm:flex-row" style={{animationDelay:'450ms'}}><Link href="/casa" className="inline-flex items-center justify-center gap-2 rounded-full bg-[#c9a85f] px-7 py-3.5 text-sm font-semibold text-[#06111c] shadow-[0_16px_50px_rgba(185,151,82,.22)] transition hover:-translate-y-1 hover:bg-[#e0c57f]">{t.casa}<ArrowRight className="size-4" /></Link><Link href="/health#book" className="inline-flex items-center justify-center gap-2 rounded-full border border-white/25 bg-white/5 px-7 py-3.5 text-sm font-medium text-white backdrop-blur transition hover:-translate-y-1 hover:border-[#c9a85f]/70 hover:text-[#e2c77f]">{t.book}<ArrowRight className="size-4" /></Link></div>
        <div className="cb-rise mt-14 flex flex-wrap gap-3 text-[.64rem] uppercase tracking-[.21em] text-white/48" style={{animationDelay:'560ms'}}><span>🇮🇹 Roma · 1893</span><span>·</span><span>🇨🇷 Costa Rica · 2024</span><span>·</span><span>🇪🇺 Europa</span></div>
      </div></div>
    </section>

    <section className="border-b border-white/10 bg-[#091724]"><div className="mx-auto max-w-7xl px-6 py-20 lg:px-10 lg:py-28"><Label>{t.heritage}</Label><div className="mt-5 grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><h2 className="max-w-3xl text-balance font-serif text-4xl font-light leading-tight sm:text-5xl">{t.heritageTitle}</h2><div className="grid gap-5 sm:grid-cols-2">{[[t.rome,'1893 · Roma','🇮🇹'],[t.costaRica,'2024 · Costa Rica','🇨🇷']].map(([body,title,flag])=><article key={title} className="rounded-3xl border border-white/10 bg-white/[.035] p-7 transition hover:-translate-y-1 hover:border-[#c9a85f]/45"><div className="flex justify-between"><Landmark className="size-5 text-[#c9a85f]" /><span className="text-2xl">{flag}</span></div><h3 className="mt-8 font-serif text-2xl">{title}</h3><p className="mt-4 text-sm leading-7 text-white/58">{body}</p></article>)}</div></div></div></section>

    <section className="relative border-b border-white/10 bg-[#f3eee3] text-[#07131f]"><div className="absolute inset-y-0 right-0 hidden w-2/5 lg:block"><Image src="/images/marble-detail.png" alt="" fill className="object-cover opacity-25" sizes="40vw" /><div className="absolute inset-0 bg-gradient-to-r from-[#f3eee3] via-[#f3eee3]/75 to-transparent" /></div><div className="relative mx-auto max-w-7xl px-6 py-20 lg:px-10 lg:py-28"><Label>{t.institution}</Label><div className="mt-6 grid gap-12 lg:grid-cols-[1fr_.9fr]"><div><h2 className="max-w-4xl text-balance font-serif text-4xl font-light leading-tight sm:text-5xl lg:text-6xl">{t.institutionTitle}</h2><p className="mt-7 max-w-2xl text-base leading-8 text-[#07131f]/65">{t.institutionBody}</p></div><div className="grid gap-px overflow-hidden rounded-3xl border border-[#07131f]/10 bg-[#07131f]/10 sm:grid-cols-2">{t.principles.map(([title,body],i)=><article key={title} className="bg-[#f8f4ec] p-7"><span className="text-[.62rem] tracking-[.22em] text-[#a3823e]">0{i+1}</span><h3 className="mt-5 font-serif text-2xl">{title}</h3><p className="mt-3 text-sm leading-6 text-[#07131f]/58">{body}</p></article>)}</div></div></div></section>

    <section className="border-b border-white/10 bg-[#06111c]"><div className="mx-auto max-w-7xl px-6 py-20 lg:px-10 lg:py-28"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><Label>{t.network}</Label><h2 className="mt-5 text-balance font-serif text-4xl font-light leading-tight sm:text-5xl">{t.networkTitle}</h2></div><p className="max-w-2xl text-base leading-8 text-white/58 lg:justify-self-end">{t.networkBody}</p></div><div className="mt-12 grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{network.map(([city,country,flag,status])=><article key={`${city}-${country}`} className="rounded-2xl border border-white/10 bg-white/[.025] p-5 transition hover:-translate-y-1 hover:border-[#c9a85f]/50 hover:bg-white/[.05]"><div className="flex justify-between"><MapPin className="size-4 text-[#c9a85f]" /><span className="text-xl">{flag}</span></div><h3 className="mt-7 font-serif text-xl">{city}</h3><p className="mt-1 text-xs text-white/45">{country}</p><p className="mt-5 inline-flex rounded-full border border-white/10 px-2.5 py-1 text-[.58rem] uppercase tracking-[.16em] text-white/48">{t.statuses[status]}</p></article>)}</div><div className="mt-8 flex gap-3 rounded-2xl border border-[#c9a85f]/20 bg-[#c9a85f]/5 p-5 text-xs leading-6 text-white/52"><ShieldCheck className="mt-0.5 size-4 shrink-0 text-[#c9a85f]" /><p>{t.networkNote}</p></div></div></section>

    <section className="border-b border-white/10 bg-[#0a1927]"><div className="mx-auto grid max-w-7xl gap-10 px-6 py-20 lg:grid-cols-[.75fr_1.25fr] lg:px-10 lg:py-24"><div className="flex items-start gap-5"><div className="flex size-16 shrink-0 items-center justify-center rounded-2xl border border-[#c9a85f]/40 bg-[#c9a85f]/8 text-3xl">🇪🇺</div><div><Label>{t.europe}</Label><p className="mt-2 text-xs uppercase tracking-[.18em] text-white/40">European institutional orientation</p></div></div><div><h2 className="text-balance font-serif text-3xl font-light sm:text-4xl">{t.europeTitle}</h2><p className="mt-6 max-w-3xl text-sm leading-7 text-white/58">{t.europeBody}</p><p className="mt-6 max-w-3xl border-l border-[#c9a85f]/45 pl-4 text-[.69rem] leading-5 text-white/38">{t.europeNote}</p></div></div></section>

    <section className="relative overflow-hidden bg-[#f4efe4] text-[#07131f]"><Image src="/images/health-calm.png" alt="Bernocchi Health consultation environment" fill className="object-cover opacity-18" sizes="100vw" /><div className="absolute inset-0 bg-gradient-to-r from-[#f4efe4] via-[#f4efe4]/94 to-[#f4efe4]/65" /><div className="relative mx-auto max-w-7xl px-6 py-24 lg:px-10 lg:py-32"><div className="max-w-3xl"><div className="flex items-center gap-3"><CheckCircle2 className="size-5 text-[#a3823e]" /><Label>{t.health}</Label></div><h2 className="mt-6 font-serif text-5xl font-light sm:text-6xl">Bernocchi Health</h2><p className="mt-6 max-w-2xl text-base leading-8 text-[#07131f]/65">{t.healthBody}</p><div className="mt-10 flex flex-col gap-4 sm:flex-row"><Link href="/health#book" className="inline-flex items-center justify-center gap-2 rounded-full bg-[#07131f] px-7 py-3.5 text-sm font-semibold text-[#f4efe4] transition hover:-translate-y-1">{t.start}<ArrowRight className="size-4" /></Link><Link href="/contact" className="inline-flex items-center justify-center gap-2 rounded-full border border-[#07131f]/20 px-7 py-3.5 text-sm font-medium transition hover:border-[#a3823e] hover:text-[#8b6d31]">{t.contact}<Building2 className="size-4" /></Link></div></div></div></section>
    <style jsx global>{`@keyframes cbRise{from{opacity:0;transform:translateY(24px)}to{opacity:1;transform:translateY(0)}}.cb-rise{opacity:0;animation:cbRise .85s cubic-bezier(.22,1,.36,1) forwards}@media(prefers-reduced-motion:reduce){.cb-rise{opacity:1;animation:none}}`}</style>
  </div>
}
